const $=id=>document.getElementById(id);
let csrf='',examples=[],meeting=null,audioTurns=null,audioText='',busy=false;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const localDate=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
$('date').value=localDate();
async function api(path,data){const res=await fetch(path,data?{method:'POST',headers:{'Content-Type':'application/json','X-Zynx-Token':csrf},body:JSON.stringify(data)}:{});const json=await res.json();if(!res.ok)throw Error(json.error||'Ошибка запроса');return json;}
function error(e){$('error').textContent=e.message||e;$('error').hidden=false;$('error').scrollIntoView({behavior:'smooth',block:'center'});}
function toast(text){$('toast').textContent=text;$('toast').hidden=false;setTimeout(()=>$('toast').hidden=true,3500);}
function switchTab(audio){$('textInput').hidden=audio;$('audioInput').hidden=!audio;$('textTab').classList.toggle('active',!audio);$('audioTab').classList.toggle('active',audio);}
$('textTab').onclick=()=>switchTab(false);$('audioTab').onclick=()=>switchTab(true);
$('mode').onchange=()=>{const ai=$('mode').value==='local';$('modelField').hidden=!ai;$('modeNotice').textContent=ai?'AI обработает текст на вашем компьютере. После извлечения второй проход проверит поручения по исходным репликам.':'Режим правил распознаёт только явно оформленные поручения. Для свободной речи выберите локальный AI.';};
function setBusy(value){busy=value;for(const id of ['analyze','transcribe','demo','newMeeting'])$(id).disabled=value;$('progress').hidden=!value;}
async function job(path,payload){$('error').hidden=true;setBusy(true);$('steps').innerHTML='';$('progressText').textContent='Подготовка';try{const {job_id}=await api(path,payload);for(;;){const state=await api('/api/jobs/'+job_id);$('progressText').textContent=state.message;$('steps').innerHTML=(state.steps||[]).map(x=>`<li>${esc(x)}</li>`).join('');if(state.state==='done')return state.result;if(state.state==='error')throw Error(state.message);await new Promise(r=>setTimeout(r,1200));}}finally{setBusy(false);}}
async function history(){const items=await api('/api/meetings');$('history').innerHTML=items.length?items.map(m=>`<button data-meeting="${m.id}">${esc(m.title)}<small>${esc(m.date)} · ${m.count} поручений</small></button>`).join(''):'<small>Здесь появятся ваши протоколы</small>';document.querySelectorAll('[data-meeting]').forEach(b=>b.onclick=async()=>{try{meeting=await api('/api/meetings/'+b.dataset.meeting);render();$('result').scrollIntoView({behavior:'smooth'});}catch(e){error(e);}});}
function applyExample(index=0){const x=examples[index];$('title').value=x.title;$('date').value=x.date;$('transcript').value=x.transcript;audioTurns=null;$('speakerMap').hidden=true;switchTab(false);$('mode').value=index===0?'rules':'local';$('mode').onchange();toast(index===0?'Синтетический пример загружен. Нажмите «Сформировать протокол».':'Для этого примера нужен локальный AI.');}
$('demo').onclick=()=>applyExample(0);
$('newMeeting').onclick=()=>{meeting=null;audioTurns=null;$('result').hidden=true;$('speakerMap').hidden=true;$('error').hidden=true;$('title').value='Рабочее совещание';$('date').value=localDate();$('transcript').value='';window.scrollTo({top:0,behavior:'smooth'});};
$('analyze').onclick=async()=>{try{const transcript=$('transcript').value.trim();if(!transcript)throw Error('Вставьте текст или нажмите «Попробовать демо».');meeting=await job('/api/analyze',{title:$('title').value,date:$('date').value,transcript,mode:$('mode').value,model:$('model').value,...(audioTurns&&transcript===audioText?{turns:audioTurns}:{})});render();await history();$('result').scrollIntoView({behavior:'smooth'});}catch(e){error(e);}};
$('transcript').addEventListener('input',()=>{if(audioTurns&&$('transcript').value!==audioText){$('speakerMap').hidden=true;}});
function updateAudioText(){audioText=audioTurns.map(t=>`${t.speaker}: ${t.text}`).join('\n');$('transcript').value=audioText;}
$('transcribe').onclick=async()=>{try{const file=$('audio').files[0];if(!file)throw Error('Выберите запись.');if(file.size>20*1024*1024)throw Error('Максимальный размер — 20 МБ.');if(!$('consent').checked)throw Error('Подтвердите согласие участников или синтетическую запись.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=reject;r.readAsDataURL(file);});const output=await job('/api/transcribe',{filename:file.name,audio:data,diarize:$('diarize').checked,speaker_count:Number($('speakers').value),language:$('language').value,consent:true});audioTurns=output.turns;updateAudioText();switchTab(false);$('mode').value='local';$('mode').onchange();const voices=[...new Set(audioTurns.map(t=>t.speaker))];$('speakerMap').innerHTML='<h3>Подпишите голоса после прослушивания</h3><p class="hint">Диаризация различает голоса. Имена участников укажите вручную.</p>'+voices.map((s,i)=>`<label>${esc(s)}<input data-voice="${i}" value="${esc(s)}"></label>`).join('')+'<button id="applyVoices" class="text-button">Применить имена</button>';$('speakerMap').hidden=!output.diarized;if(output.diarized){const original=audioTurns.map(t=>({...t}));$('applyVoices').onclick=()=>{const values=[...document.querySelectorAll('[data-voice]')].map(x=>x.value.trim().replace(/[:\n]/g,' ')||'Не определён');audioTurns=original.map(t=>({...t,speaker:values[voices.indexOf(t.speaker)]}));updateAudioText();toast('Имена применены');};}toast('Транскрипт готов. Проверьте его и сформируйте протокол.');}catch(e){error(e);}};
function overdue(t){return t.due_date&&t.due_date<localDate()&&t.status!=='Выполнено';}
function render(){const r=meeting.result;$('result').hidden=false;$('resultTitle').textContent=meeting.title;$('resultMeta').textContent=`${meeting.date} · ${meeting.mode==='local'?'Локальный AI':'Правила, без AI'} · Черновик`;$('warnings').innerHTML=(r.warnings||[]).map(w=>`<div class="notice">${esc(w)}</div>`).join('');$('summary').value=r.summary;$('decisions').innerHTML=r.decisions?.length?'<h3>Решения</h3><ul>'+r.decisions.map(x=>`<li>${esc(x)}</li>`).join('')+'</ul>':'';$('total').textContent=r.tasks.length;$('review').textContent=r.tasks.filter(t=>!t.reviewed).length;$('overdue').textContent=r.tasks.filter(overdue).length;$('done').textContent=r.tasks.filter(t=>t.status==='Выполнено').length;
$('tasks').innerHTML=r.tasks.length?r.tasks.map((t,i)=>`<article class="task" data-id="${t.id}"><div class="task-top"><span class="task-num">${String(i+1).padStart(2,'0')}</span><label class="sr-only" for="task-${t.id}">Поручение ${i+1}</label><input class="task-title" id="task-${t.id}" data-field="task" value="${esc(t.task)}"></div><div class="task-fields"><label>Ответственный<input data-field="owner" value="${esc(t.owner)}"></label><label>Срок из разговора<input data-field="due_text" value="${esc(t.due_text)}"></label><label>Уточнённая дата<input data-field="due_date" type="date" value="${esc(t.due_date||'')}"></label><label>Статус<select data-field="status"><option${t.status==='В работе'?' selected':''}>В работе</option><option${t.status==='Выполнено'?' selected':''}>Выполнено</option></select></label></div><blockquote class="evidence"><small>ОСНОВАНИЕ · РЕПЛИКИ ${(t.source_ids||[]).join(', ')}</small>${esc(t.evidence)}</blockquote>${t.issues?.length?`<div class="issues">Проверка при извлечении: ${t.issues.map(esc).join(' · ')}</div>`:''}<div class="review-line"><label class="check"><input data-field="reviewed" type="checkbox"${t.reviewed?' checked':''}> Проверено человеком</label><span class="badge ${overdue(t)?'late':''}">${overdue(t)?'Просрочено':t.due_date?'Дата указана':'Уточнить срок'}</span></div></article>`).join(''):'<div class="panel"><h3>Поручения не найдены</h3><p>Для свободной речи используйте локальный AI. В режиме правил требуется формат: действие — ответственный Имя; срок дата.</p></div>';
$('trace').innerHTML=(meeting.trace||[]).map(esc).join(' → ');$('source').innerHTML=meeting.turns.map(t=>`<div class="turn"><strong>[${t.id}] ${esc(t.speaker)}${t.start!=null?' · '+Math.floor(t.start/60)+':'+String(Math.floor(t.start%60)).padStart(2,'0'):''}</strong>${esc(t.text)}</div>`).join('');}
async function save(){if(!meeting)return;const tasks=[...document.querySelectorAll('.task')].map(el=>{const t={id:el.dataset.id};el.querySelectorAll('[data-field]').forEach(x=>t[x.dataset.field]=x.type==='checkbox'?x.checked:x.value);return t;});meeting=await api('/api/save',{id:meeting.id,tasks,summary:$('summary').value});render();await history();}
$('save').onclick=async()=>{try{await save();toast('Правки сохранены');}catch(e){error(e);}};
document.querySelectorAll('.export').forEach(b=>b.onclick=async()=>{try{b.disabled=true;await save();const fmt=b.dataset.format;const res=await fetch(`/api/meetings/${meeting.id}/${fmt}`);if(!res.ok){const data=await res.json();throw Error(data.error);}const url=URL.createObjectURL(await res.blob());const a=document.createElement('a');a.href=url;a.download='ZYNX-protocol.'+fmt;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Протокол скачан');}catch(e){error(e);}finally{b.disabled=false;}});
$('delete').onclick=async()=>{if(meeting&&confirm('Удалить это совещание с компьютера?')){try{await api('/api/delete',{id:meeting.id});meeting=null;$('result').hidden=true;await history();toast('Совещание удалено');}catch(e){error(e);}}};
async function init(){try{const config=await api('/api/config');csrf=config.csrf;examples=await api('/api/examples');$('systemStatus').innerHTML=`Whisper: ${config.whisper?'модель на диске':'нужна установка'}<br>Диаризация: ${config.diarization?'модель на диске':'нужна установка'}<br>PDF / DOCX: ${config.export?'доступны':'установите requirements.txt'}<br><span>Настройка моделей — в README проекта.</span>`;await history();}catch(e){error(e);}}init();
